@url = https://api.stlouisfed.org/fred/series/observations

@key = 

### 1-Month Treasury
GET {{url}}?series_id=DGS1MO&api_key={{key}}&file_type=json&observation_start=2026-02-06&observation_end=2026-02-06
Accept: application/json